# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "tvdeyen-handles_sortable_columns"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Fortuna", "Thomas von Deyen"]
  s.date = "2013-03-27"
  s.description = "Sortable Table Columns"
  s.email = "tvdeyen@gmail.com"
  s.extra_rdoc_files = [
    "README.html",
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.html",
    "README.md",
    "Rakefile",
    "VERSION.yml",
    "init.rb",
    "lib/action_controller/base/handles_sortable_columns.rb",
    "lib/handles/sortable_columns.rb",
    "lib/handles_sortable_columns.rb",
    "tvdeyen-handles_sortable_columns.gemspec"
  ]
  s.homepage = "https://github.com/tvdeyen/handles_sortable_columns"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Sortable Table Columns"
end

